name: Frontend CI/CD Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout código
        uses: actions/checkout@v4

      - name: 🎨 Desplegar Frontend en VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            echo "🚀 Desplegando frontend en producción..."
            cd ~/athenia-clean/athenia-frontend
            npm install --legacy-peer-deps
            npm run build
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            sudo systemctl restart nginx
            echo "✅ Frontend desplegado correctamente."
